// Book actions
export const GET_BOOKS = 'GET_BOOKS';
export const SELECTED_BOOK = 'SELECTED_BOOK';
export const SEARCH_SELECTED_BOOK = 'SEARCH_SELECTED_BOOK';
export const SEARCH_BOOK = 'SEARCH_BOOK';
export const FETCH_MORE_RESULTS = 'FETCH_MORE_RESULTS';
export const REMOVE_BOOK = 'REMOVE_BOOK';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

// Club Actions
export const GET_CLUBS = 'GET_CLUBS';
export const JOIN_CLUB = 'JOIN_CLUB';
export const LEAVE_CLUB = 'LEAVE_CLUB';
export const CREATE_CLUB = 'CREATE_CLUB';

// Comments count Actions
export const GET_COMMENTS_COUNT = 'GET_COMMENTS_COUNT';
export const GET_COMMENTS_COUNT_REQUEST = 'GET_COMMENTS_COUNT_REQUEST';
export const GET_COMMENTS_COUNT_RESPONSE = 'GET_COMMENTS_COUNT_RESPONSE';
export const GET_COMMENTS_COUNT_ERROR = 'GET_COMMENTS_COUNT_ERROR';

export const ADD_LAST_SEEN = 'ADD_LAST_SEEN';

// Auth Actions
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_RESPONSE = 'SIGN_UP_RESPONSE';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const VALIDATE_PASSWORD_RECOVERY = 'VALIDATE_PASSWORD_RECOVERY';
export const VALIDATE_PASSWORD_RECOVERY_REQUEST =
  'VALIDATE_PASSWORD_RECOVERY_REQUEST';
export const VALIDATE_PASSWORD_RECOVERY_RESPONSE =
  'VALIDATE_PASSWORD_RECOVERY_RESPONSE';
export const VALIDATE_PASSWORD_RECOVERY_ERROR =
  'VALIDATE_PASSWORD_RECOVERY_ERROR';

export const PASSWORD_RECOVERY = 'PASSWORD_RECOVERY';
export const PASSWORD_RECOVERY_REQUEST = 'PASSWORD_RECOVERY_REQUEST';
export const PASSWORD_RECOVERY_RESPONSE = 'PASSWORD_RECOVERY_RESPONSE';
export const PASSWORD_RECOVERY_ERROR = 'PASSWORD_RECOVERY_ERROR';

export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_RESPONSE = 'PASSWORD_RESET_RESPONSE';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';

export const REGISTER_PUSH_NOTIFICATION_TOKEN =
  'REGISTER_PUSH_NOTIFICATION_TOKEN';
export const REGISTER_PUSH_NOTIFICATION_TOKEN_REQUEST =
  'REGISTER_PUSH_NOTIFICATION_TOKEN_REQUEST';
export const REGISTER_PUSH_NOTIFICATION_TOKEN_RESPONSE =
  'REGISTER_PUSH_NOTIFICATION_TOKEN_RESPONSE';
export const REGISTER_PUSH_NOTIFICATION_TOKEN_ERROR =
  'REGISTER_PUSH_NOTIFICATION_TOKEN_ERROR';

export const REMOVE_PUSH_NOTIFICATION_TOKEN = 'REMOVE_PUSH_NOTIFICATION_TOKEN';
export const REMOVE_PUSH_NOTIFICATION_TOKEN_REQUEST =
  'REMOVE_PUSH_NOTIFICATION_TOKEN_REQUEST';
export const REMOVE_PUSH_NOTIFICATION_TOKEN_RESPONSE =
  'REMOVE_PUSH_NOTIFICATION_TOKEN_RESPONSE';
export const REMOVE_PUSH_NOTIFICATION_TOKEN_ERROR =
  'REMOVE_PUSH_NOTIFICATION_TOKEN_ERROR';

export const REMOVE_LOADING = 'REMOVE_LOADING';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_RESPONSE = 'SIGN_IN_RESPONSE';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_RESPONSE = 'GET_PROFILE_RESPONSE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const SIGN_OUT = 'SIGN_OUT';
